import { useEffect, useRef, useState } from 'react';
import { AlertTriangle, CheckCircle2, Database, Download, HardDrive, History, RotateCcw, Trash2, Upload, X } from 'lucide-react';
import { Button } from '@/shared/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/shared/components/ui/card';
import { ModulePageShell, StatusBadge } from '@/shared/components/ModulePageShell';
import { backupApi, type BackupItem } from '@/modules/core/services/backup';
import api from '@/shared/services/api';

const formatBytes = (bytes: number) => { if (!bytes) return '0 B'; const units = ['B', 'KB', 'MB', 'GB', 'TB']; const i = Math.floor(Math.log(bytes) / Math.log(1024)); return `${(bytes / 1024 ** i).toFixed(i ? 1 : 0)} ${units[i]}`; };
const baseUrl = `${import.meta.env.VITE_CORE_MODULE_URL || 'core/module/v1'}/Backup`;

export default function BackupRestorePage() {
  const [backups, setBackups] = useState<BackupItem[]>([]);
  const [retentionDays, setRetentionDays] = useState(30);
  const [showRestore, setShowRestore] = useState(false);
  const [selectedBackup, setSelectedBackup] = useState('');
  const [creating, setCreating] = useState(false);
  const [busy, setBusy] = useState('');
  const [error, setError] = useState('');
  const fileRef = useRef<HTMLInputElement>(null);

  const load = async () => { try { setError(''); const data = await backupApi.list(); setBackups(data.items ?? []); setRetentionDays(data.retentionDays ?? 30); } catch (e: any) { setError(e?.message ?? 'Unable to load backup history.'); } };
  useEffect(() => { void load(); }, []);
  const createBackup = async () => { setCreating(true); setError(''); try { await backupApi.create(); await load(); } catch (e: any) { setError(e?.message ?? 'Backup creation failed.'); } finally { setCreating(false); } };
  const download = async (name: string) => { setBusy(`download:${name}`); try { const response = await api.get(`${baseUrl}/Download/${encodeURIComponent(name)}`, { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); } catch (e: any) { setError(e?.message ?? 'Download failed.'); } finally { setBusy(''); } };
  const remove = async (name: string) => { setBusy(`delete:${name}`); try { await backupApi.remove(name); await load(); } catch (e: any) { setError(e?.message ?? 'Delete failed.'); } finally { setBusy(''); } };
  const restore = async () => { setBusy(`restore:${selectedBackup}`); try { await backupApi.restore(selectedBackup); setShowRestore(false); await load(); } catch (e: any) { setError(e?.message ?? 'Restore failed.'); } finally { setBusy(''); } };
  const upload = async (file?: File) => { if (!file) return; setBusy('upload'); try { await backupApi.upload(file); await load(); } catch (e: any) { setError(e?.message ?? 'Upload failed.'); } finally { setBusy(''); if (fileRef.current) fileRef.current.value = ''; } };
  const storage = backups.reduce((sum, b) => sum + b.sizeBytes, 0);
  const last = backups[0];

  return (
    <ModulePageShell title="Backup & Restore" subtitle="Protect the Core database with controlled backups and administrator-only recovery operations." onRefresh={load} primaryActionLabel={creating ? 'Creating...' : 'Create Backup'} onPrimaryAction={() => void createBackup()}>
      {error && <div className="mb-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
      <div className="space-y-5">
        <div className="grid gap-4 md:grid-cols-3">
          <Card className="border-slate-200 shadow-none"><CardContent className="flex items-center gap-4 p-5"><Database className="h-7 w-7 text-emerald-600" /><div><p className="text-xs uppercase tracking-wide text-slate-500">Last Backup</p><p className="mt-1 font-semibold text-slate-900">{last ? new Date(last.createdAt).toLocaleString() : 'No backup yet'}</p><p className="text-xs text-slate-400">{last ? formatBytes(last.sizeBytes) : 'Create the first backup'}</p></div></CardContent></Card>
          <Card className="border-slate-200 shadow-none"><CardContent className="flex items-center gap-4 p-5"><HardDrive className="h-7 w-7 text-sky-600" /><div><p className="text-xs uppercase tracking-wide text-slate-500">Storage Used</p><p className="mt-1 font-semibold text-slate-900">{formatBytes(storage)}</p><p className="text-xs text-slate-400">{backups.length} backup file{backups.length === 1 ? '' : 's'}</p></div></CardContent></Card>
          <Card className="border-slate-200 shadow-none"><CardContent className="flex items-center gap-4 p-5"><History className="h-7 w-7 text-amber-600" /><div><p className="text-xs uppercase tracking-wide text-slate-500">Retention</p><p className="mt-1 font-semibold text-slate-900">{retentionDays} days</p><p className="text-xs text-slate-400">Automatic cleanup on new backups</p></div></CardContent></Card>
        </div>
        <Card className="border-slate-200 shadow-none"><CardHeader><CardTitle className="text-base">Backup History</CardTitle><p className="text-sm text-slate-500">PostgreSQL custom-format backups available for download or restoration.</p></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-y bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Backup</th><th className="px-5 py-3">Size</th><th className="px-5 py-3">Created</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{backups.map((backup) => <tr key={backup.id}><td className="px-5 py-4"><div className="font-medium text-slate-800">{backup.name}</div><div className="text-xs text-slate-400">Core database</div></td><td className="px-5 py-4 text-slate-600">{formatBytes(backup.sizeBytes)}</td><td className="px-5 py-4 text-slate-600">{new Date(backup.createdAt).toLocaleString()}</td><td className="px-5 py-4"><StatusBadge status={backup.status} tone="success" /></td><td className="px-5 py-4"><div className="flex justify-end gap-1"><Button size="sm" variant="ghost" title="Download" disabled={busy === `download:${backup.name}`} onClick={() => void download(backup.name)}><Download className="h-4 w-4" /></Button><Button size="sm" variant="ghost" title="Restore" onClick={() => { setSelectedBackup(backup.name); setShowRestore(true); }}><RotateCcw className="h-4 w-4" /></Button><Button size="sm" variant="ghost" title="Delete" disabled={busy === `delete:${backup.name}`} onClick={() => void remove(backup.name)}><Trash2 className="h-4 w-4 text-rose-500" /></Button></div></td></tr>)}{!backups.length && <tr><td colSpan={5} className="px-5 py-12 text-center text-sm text-slate-500">No backups found.</td></tr>}</tbody></table></div></CardContent></Card>
        <Card className="border-amber-200 bg-amber-50/50 shadow-none"><CardContent className="flex gap-3 p-4"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-600" /><div><p className="font-medium text-amber-900">Restore is destructive</p><p className="mt-1 text-sm text-amber-800">Always create a current backup before restoring. Restore operations are restricted to administrator roles.</p></div></CardContent></Card>
        <div className="grid gap-4 md:grid-cols-2"><Card className="border-slate-200 shadow-none"><CardHeader><CardTitle className="text-base">Upload Backup</CardTitle></CardHeader><CardContent><input ref={fileRef} type="file" accept=".dump" className="hidden" onChange={(e) => void upload(e.target.files?.[0])} /><div className="rounded-xl border-2 border-dashed border-slate-200 p-8 text-center"><Upload className="mx-auto h-8 w-8 text-slate-400" /><p className="mt-3 font-medium text-slate-700">Upload a PostgreSQL .dump file</p><Button variant="outline" className="mt-4" disabled={busy === 'upload'} onClick={() => fileRef.current?.click()}>{busy === 'upload' ? 'Uploading...' : 'Choose File'}</Button></div></CardContent></Card><Card className="border-slate-200 shadow-none"><CardHeader><CardTitle className="text-base">Recovery Readiness</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex items-center gap-3 rounded-lg bg-emerald-50 p-3"><CheckCircle2 className="h-5 w-5 text-emerald-600" /><div><p className="text-sm font-medium text-emerald-900">Backup service connected</p><p className="text-xs text-emerald-700">{backups.length ? 'A valid backup inventory is available.' : 'No backup has been created yet.'}</p></div></div><p className="text-xs text-slate-500">The service uses PostgreSQL custom-format dumps and keeps files under the configured backup storage path.</p></CardContent></Card></div>
      </div>
      {showRestore && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl"><div className="flex items-start justify-between"><div><h2 className="text-lg font-semibold text-slate-900">Confirm Restore</h2><p className="mt-1 text-sm text-slate-500">This will replace objects in the Core database.</p></div><button onClick={() => setShowRestore(false)}><X className="h-5 w-5 text-slate-400" /></button></div><div className="mt-5 rounded-lg border border-amber-200 bg-amber-50 p-3"><p className="text-sm font-medium text-amber-900">{selectedBackup}</p><p className="mt-1 text-xs text-amber-800">Create a fresh backup first if you need a rollback point.</p></div><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={() => setShowRestore(false)}>Cancel</Button><Button variant="destructive" disabled={busy === `restore:${selectedBackup}`} onClick={() => void restore()}><RotateCcw className="mr-2 h-4 w-4" />{busy === `restore:${selectedBackup}` ? 'Restoring...' : 'Confirm Restore'}</Button></div></div></div>}
    </ModulePageShell>
  );
}
